# Generated by Django 2.0 on 2018-08-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('description', models.TextField(max_length=100)),
                ('image', models.ImageField(max_length=300, upload_to='')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
