# Generated by Django 2.0 on 2018-08-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallary1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.FileField(max_length=300, upload_to=''),
        ),
    ]
